Publish v6.0.17 and v6.2.10. [release]
CircleCI-Public/cimg-redis pull request #27
Opened 2023-01-17 15:55 UTC by BytesGuy

2023-01-17 20:01 UTC, JalexChen requested changes

2023-01-17 20:01 UTC, JalexChen commented on 6.0/Dockerfile
> +FROM cimg/base:2022.11
This should be cimg/base:2023.01

2023-01-17 22:22 UTC, BytesGuy commented on 6.0/Dockerfile
> +FROM cimg/base:2022.11
Bumped

2023-01-20 17:04 UTC, JalexChen approved these changes

2023-01-20 17:04 UTC, merged